# Usa una imagen base de OpenJDK
FROM openjdk:17-jdk-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo JAR generado por Maven al contenedor
COPY target/auth-service-0.0.1-SNAPSHOT.jar auth-service.jar

# Expone el puerto en el que el servicio estará disponible
EXPOSE 8080

# Comando para ejecutar el servicio cuando se inicie el contenedor
ENTRYPOINT ["java", "-jar", "auth-service.jar"]
