services:

  # Eureka Server
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-net

  # Api Gateway
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - eureka-server


  # User Service
  usuario-service:
    build:
      context: ./usuario-service
    container_name: usuario-service
    ports:
      - "8081:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - usuario-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://usuario-db:3306/usuario_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  # Base de datos MySQL para usuario-service
  usuario-db:
    image: mysql:8.0
    container_name: usuario-db
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: usuario_db
    networks:
      - spring-cloud-net


  # Monopatin Service
  monopatin-service:
    build:
      context: ./monopatin-service
    container_name: monopatin-service
    ports:
      - "8082:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - monopatin-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://monopatin-db:27017/monopatin_db

  # Base de datos MongoDB para monopatin-service
  monopatin-db:
    image: mongo:latest
    container_name: monopatin-db
    ports:
      - "27017:27017"  # Puerto estándar de MongoDB
    restart: unless-stopped
    networks:
      - spring-cloud-net


  # Viaje Service
  viaje-service:
    build:
      context: ./viaje-service
    container_name: viaje-service
    ports:
      - "8083:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - viaje-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://viaje-db:3306/viaje_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  # Base de datos MySQL para viaje-service
  viaje-db:
    image: mysql:8.0
    container_name: viaje-db
    ports:
      - "3307:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: viaje_db
    networks:
      - spring-cloud-net


 # Parada Service
  parada-service:
    build:
      context: ./parada-service
    container_name: parada-service
    ports:
      - "8084:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - parada-db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://parada-db:27017/parada_db

  # Base de datos MongoDB para parada-service
  parada-db:
    image: mongo:latest
    container_name: parada-db
    ports:
      - "27018:27017"  # Puerto para el segundo contenedor de MongoDB
    restart: unless-stopped
    networks:
      - spring-cloud-net


  # Mantenimiento Service
  mantenimiento-service:
    build:
      context: ./mantenimiento-service
    container_name: mantenimiento-service
    ports:
      - "8085:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - mantenimiento-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mantenimiento-db:3306/mantenimiento_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  # Base de datos MySQL para mantenimiento-service
  mantenimiento-db:
    image: mysql:8.0
    container_name: mantenimiento-db
    ports:
      - "3309:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mantenimiento_db
    networks:
      - spring-cloud-net


  # Auth Service
  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8086:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - auth-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://auth-db:3306/auth_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  # Base de datos MySQL para auth-service
  auth-db:
    image: mysql:8.0
    container_name: auth-db
    ports:
      - "3310:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: auth_db
    networks:
      - spring-cloud-net


  # Admin Service
  admin-service:
    build:
      context: ./admin-service
    container_name: admin-service
    ports:
      - "8087:8080"
    networks:
      - spring-cloud-net
    depends_on:
      - admin-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://admin-db:3306/admin_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  # Base de datos MySQL para auth-service
  admin-db:
    image: mysql:8.0
    container_name: admin-db
    ports:
      - "3311:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: admin_db
    networks:
      - spring-cloud-net
      
networks:
  spring-cloud-net:
